#!/usr/bin/env python3
"""In-kernel opaque-primitive sizing.

The opaque kernel primitives (spinlock_t, struct mutex, atomic_t, list_head, ...)
have CONFIG-DEPENDENT sizes — spinlock_t is 4 bytes with no debug options, but
grows under PROVE_LOCKING/DEBUG_SPINLOCK/LOCKDEP. So the mirror generator cannot
guess their layout on the host; it REFUSES them. This module measures the REAL
sizes from the REAL kernel build, soundly:

  1. Emit a tiny probe.c compiled *inside the kernel build* (real headers, real
     .config) with, per primitive T:
         char cgir_sz_<tag>[sizeof(T)];
         char cgir_al_<tag>[__alignof__(T)];
     Each array's *symbol size* in the ELF table equals the value we want —
     no printf, no execution, just compile + read the symbol table.
  2. Read the symbol sizes with `nm --print-size` on the resulting object.
  3. Write primitive_sizes.json = { "spinlock_t": [size, align], ... }.

The mirror generator then emits an opaque field as an array of the alignment-
matching integer ([u64; size/8] for align-8, [u32; size/4] for align-4, ...),
giving BOTH correct size AND correct alignment so the *parent* struct's field
offsets are right. The existing two-legged mirror gate (rustc const-asserts +
kernel BUILD_BUG_ON on the parent's sizeof/offsetof) then RE-CERTIFIES every
emitted layout against the real kernel — a wrong probe value cannot pass the
gate. The kernel itself is the oracle for these sizes.

Soundness note: the measured sizes are valid for the .config they were probed
against — the SAME .config the mirror gate's kernel leg builds with (the
cgir-kbuild volume). Probe and re-certification are on one config, so they are
consistent by construction. Re-probe on a config change.
"""
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
CACHE = os.path.join(HERE, "primitive_sizes.json")

# (C type, header that defines it). tag = sanitized type name.
PRIMITIVES = [
    ("spinlock_t", "linux/spinlock.h"),
    ("raw_spinlock_t", "linux/spinlock.h"),
    ("rwlock_t", "linux/rwlock.h"),
    ("seqlock_t", "linux/seqlock.h"),
    ("seqcount_t", "linux/seqlock.h"),
    ("atomic_t", "linux/atomic.h"),
    ("atomic64_t", "linux/atomic.h"),
    ("atomic_long_t", "linux/atomic.h"),
    ("refcount_t", "linux/refcount.h"),
    ("wait_queue_head_t", "linux/wait.h"),
    ("struct mutex", "linux/mutex.h"),
    ("struct rw_semaphore", "linux/rwsem.h"),
    ("struct semaphore", "linux/semaphore.h"),
    ("struct completion", "linux/completion.h"),
    ("struct list_head", "linux/types.h"),
    ("struct hlist_head", "linux/types.h"),
    ("struct hlist_node", "linux/types.h"),
    ("struct rcu_head", "linux/types.h"),
    ("struct llist_head", "linux/llist.h"),
    ("struct llist_node", "linux/llist.h"),
    ("struct kref", "linux/kref.h"),
    ("struct work_struct", "linux/workqueue.h"),
    ("struct delayed_work", "linux/workqueue.h"),
    ("struct timer_list", "linux/timer.h"),
    ("struct hrtimer", "linux/hrtimer.h"),
    ("struct rb_root", "linux/rbtree.h"),
    ("struct rb_node", "linux/rbtree.h"),
    ("struct callback_head", "linux/types.h"),
]

# Umbrella headers pull in almost everything above transitively; probing inside
# a real kernel build these resolve. Kept explicit and broad so a missing type
# fails loudly at compile rather than silently vanishing.
HEADERS = [
    "linux/kernel.h", "linux/types.h", "linux/spinlock.h", "linux/rwlock.h",
    "linux/seqlock.h", "linux/mutex.h", "linux/rwsem.h", "linux/semaphore.h",
    "linux/completion.h", "linux/atomic.h", "linux/refcount.h", "linux/wait.h",
    "linux/list.h", "linux/llist.h", "linux/rbtree.h", "linux/kref.h",
    "linux/workqueue.h", "linux/timer.h", "linux/hrtimer.h",
]


def tag_of(ctype):
    return re.sub(r"\W+", "_", ctype).strip("_")


def emit_probe_c(primitives=PRIMITIVES):
    lines = ["/* AUTO-GENERATED by probe_primitives.py — in-kernel size probe. */"]
    lines += [f"#include <{h}>" for h in HEADERS]
    lines.append("")
    for ctype, _ in primitives:
        t = tag_of(ctype)
        lines.append(f"char cgir_sz_{t}[sizeof({ctype})];")
        lines.append(f"char cgir_al_{t}[__alignof__({ctype})];")
    return "\n".join(lines) + "\n"


def parse_nm(nm_out, primitives=PRIMITIVES):
    """nm --print-size lines: `<value> <size> <type> <name>`. Symbol size = value."""
    sizes = {}
    for line in nm_out.splitlines():
        parts = line.split()
        if len(parts) < 4:
            continue
        try:
            sz = int(parts[1], 16)
        except ValueError:
            continue
        sizes[parts[-1]] = sz
    result = {}
    for ctype, _ in primitives:
        t = tag_of(ctype)
        s, a = sizes.get(f"cgir_sz_{t}"), sizes.get(f"cgir_al_{t}")
        if s is not None and a is not None:
            result[ctype] = [s, a]
    return result


def run_probe():
    """Build the probe inside the kernel and read the symbol table. Returns dict."""
    os.makedirs(OUT, exist_ok=True)
    open(os.path.join(OUT, "probe.c"), "w").write(emit_probe_c())
    vol, img, gate = "cgir-kbuild", "cgir-kernel-gate", "crypto/lockstep_gate"
    # Stage the probe into the kernel tree (own Kbuild), build it, dump symbols.
    subprocess.run([
        "docker", "run", "--rm", "-v", f"{vol}:/build", "-v", f"{OUT}:/o:ro", img,
        "bash", "-euc",
        f"cd /build/linux; mkdir -p {gate}; "
        f"grep -q 'obj-y += lockstep_gate/' crypto/Makefile || echo 'obj-y += lockstep_gate/' >> crypto/Makefile; "
        f"cd {gate}; rm -f probe.c probe.o; cp /o/probe.c .; printf 'obj-y := probe.o\\n' > Kbuild",
    ], check=True)
    out = subprocess.run([
        "docker", "run", "--rm", "-v", f"{vol}:/build", img,
        "bash", "-eo", "pipefail", "-uc",
        f"cd /build/linux && make -s {gate}/probe.o 2>&1 | tail -3 && "
        f"nm --print-size --defined-only {gate}/probe.o",
    ], check=True, capture_output=True, text=True)
    sizes = parse_nm(out.stdout)
    if not sizes:
        sys.stderr.write("probe produced no sizes:\n" + out.stdout + "\n")
        raise SystemExit(1)
    return sizes


def load_cache():
    if os.path.isfile(CACHE):
        return json.load(open(CACHE))
    return {}


def main():
    sizes = run_probe()
    json.dump(sizes, open(CACHE, "w"), indent=2, sort_keys=True)
    print(f"-> {os.path.relpath(CACHE)}  ({len(sizes)}/{len(PRIMITIVES)} primitives sized)")
    for ctype, (s, a) in sorted(sizes.items()):
        print(f"   {ctype:28s} size={s:3d} align={a}")
    missing = [c for c, _ in PRIMITIVES if c not in sizes]
    if missing:
        print("   MISSING (did not compile/resolve):", ", ".join(missing))


if __name__ == "__main__":
    main()
